name: CI

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dart-lang/setup-dart@v1

      # Get packages.
      - run: dart pub get

      # Validate manifests.
      - run: dart run tool/repo.dart validate-manifests

      # Dart checks.
      - run: dart analyze
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart test
